version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./path/to/frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build: 
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./path/to/backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
