version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  backend:
    build: 
      context: ./backend
    ports:
      - "3388:3388"
    volumes:
      - ./backend:/usr/src/app
